modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="contamination"
version="${mod_version}"
displayName="Contamination"
description='Adds contamination and a Lugol item to protect players.'
authors="sSwpl"

[[dependencies.contamination]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.contamination]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.contamination]]
modId="jei"
type="optional"
versionRange="[19,)"
ordering="NONE"
side="CLIENT"
