name: Build (Forge 1.20.1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure Gradle wrapper exists (generate if missing)
        shell: bash
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle wrapper missing. Generating with Gradle 8.1.1..."
            curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.1.1-bin.zip
            unzip -q gradle.zip -d "$RUNNER_TEMP/gradle"
            "$RUNNER_TEMP/gradle/gradle-8.1.1/bin/gradle" wrapper --gradle-version 8.1.1
          else
            echo "Gradle wrapper present."
          fi
          chmod +x ./gradlew

      - name: Setup Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew --refresh-dependencies clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contamination-mod-jars
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar