name: Build (Forge 1.20.1)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure Gradle wrapper exists (if missing)
        run: |
          if [ ! -f "./gradlew" ]; then
            curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.1.1-bin.zip
            unzip -q gradle.zip -d "$RUNNER_TEMP/gradle"
            "$RUNNER_TEMP/gradle/gradle-8.1.1/bin/gradle" wrapper --gradle-version 8.1.1
          fi
          chmod +x ./gradlew

      - name: Build
        run: ./gradlew --no-daemon --refresh-dependencies clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contamination-mod-jars
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar